export const bucketsUrl = 'http://rs.qbox.me/buckets'
export const dropUrl = 'http://rs.qbox.me/drop/'
export const addUrl = 'http://rs.qiniu.com/mkbucketv2/'
export const deleteUrl = 'http://rs.qiniu.com/delete/'
export const listUrl = 'http://rsf.qbox.me/list'